### ISSUE TITLE
`\n` in format-string doesn't print newline

### ISSUE THREAD

**Issue by subnut** [emersion/slurp#102]
The manpage shows that -
```
The default format is "%x,%y %wx%h\n"
```
which contains a trailing newline that corresponds the the newline at the end of the output..

But, if we run -
```
slurp -f "%x %y\n"
```
It prints -
```
1220 642\n
```
**WITHOUT** a trailing newline. (The `\n` is printed as-is)

---

Since there is no trailing newline, piping the result into the _shell builtin_ `read` doesn't work.

**Comment by tmccombs** [comment]
slurp doesn't handle backslash escapes itself, you'll need to escape it at the shell level. For example in bash or zsh you would do:

```
slurp -f $'%x %y\n'
```

I'm going to go ahead and close this issue, but if you think there is something that still needs to be done, we can re-open it.

**Comment by subnut** [comment]
Okay, makes sense. But shouldn't it be mentioned somewhere in the manpage?

**Comment by subnut** [comment]
@tmccombs This doesn't work -
```sh
slurp -f "%x %y$(printf '\n')"
```

**Comment by tmccombs** [comment]
That's because `$(printf '\n')` strips the trailing newline.

**Comment by tmccombs** [comment]
> But shouldn't it be mentioned somewhere in the manpage?

Made a PR to add it to the manpage.
