### ISSUE TITLE
slurp: ../main.c:479: main: Assertion `cursor' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by CosmoJG** [emersion/slurp#11]
I am unable to run slurp on the latest build of Sway with wlroots on Arch Linux. Slurp fails to function and quits with the following error:

```
slurp: ../main.c:479: main: Assertion `cursor' failed.

Aborted (core dumped)
```

**Comment by emersion** [comment]
Ah, seems like your cursor theme is missing the `crosshair` cursor. We probably want to replace these assertions with real error messages and fallback to the `left_ptr` cursor.

**Comment by SirCmpwn** [comment]
Error message has got a line of code, what more do you need

**Comment by emersion** [comment]
I don't like using assertions for things like this. It doesn't explain what went wrong to the user, and it's designed to be used to catch bugs (not failures).

**Comment by emersion** [comment]
Also consider that programs can be compiled without assertions, that would remove all error checking.

**Comment by SirCmpwn** [comment]
Compiling code without assertions is just asking for problems
