### ISSUE TITLE
Consider a version bump

### ISSUE THREAD

**Issue by voidbert** [emersion/slurp#118]
[Version 1.3.2](https://github.com/emersion/slurp/releases/tag/v1.3.2) was released in April of last year. Since then, many features have been added, such as [local coordinates](https://github.com/emersion/slurp/commit/956c9c91ae80e7c487097ca712839e7fc80dd9ae) and [fixed aspect ratio support](https://github.com/emersion/slurp/commit/f4e75594c3234519fe8b795a1163dfa31d2e7f3a).

I personally needed this last feature, and had to build slurp from source. A new release would allow distros to package these new features for users. As of now, they aren't available on rolling distros (such as [Arch](https://archlinux.org/packages/community/x86_64/slurp/) and [Void](https://github.com/void-linux/void-packages/blob/master/srcpkgs/slurp/template)), as the code is likely thought to be experimental git code (available through the AUR as [slurp-git](https://aur.archlinux.org/packages/slurp-git), for example).

My suggestion is to create a new release tag, provided the new features added and the time since the last release. As I'm unaware of slurp's versioning number scheme, it could likely be 1.4.0 or 1.3.3.

**Comment by emersion** [comment]
https://github.com/emersion/slurp/releases/tag/v1.4.0
