### ISSUE TITLE
Cannot select an area within (some?) XWayland games/applications

### ISSUE THREAD

**Issue by Fleimi** [emersion/slurp#125]
Slurp seems to be unable to select an area inside of most games I've tried. For example, in Final Fantasy XIV, calling `grim -g "$(slurp -w 0)" - | wl-copy` whitens the screen indicating a selection is taking place, but clicking and dragging inside the game doesn't select anything and the selection mode doesn't end. Moreover, trying the press `Escape` to cancel the selection also doesn't do anything. The only way to back out of the screenshot is to switch to another workspace and press `Escape` or select an area as normal and make a successful selection/screenshot.

**Comment by tmccombs** [comment]
That might be a bug in sway or wlroots.

**Comment by Fleimi** [comment]
I’m using Hyprland, so I’m guessing wlroots in case it turns out to not be directly a slurp thing.

**Comment by Fleimi** [comment]
Tested within sway, slurp + grim work as intended. Ruling out wlroots and suspecting now a Hyprland-specific issue.
