### ISSUE TITLE
ShareX-style aiming

### ISSUE THREAD

**Issue by jeremejevs** [emersion/slurp#13]
It has a lot of features worth borrowing, but there's one that I keep remembering about:

![](https://i.imgur.com/7GV34Bu.png)

Before and during the selection process, there's a zoomed preview of the area your mouse is in, highlighting the pixel you're currently aiming at. Very useful for quick pixel-perfect screenshots, which I currently have to either redo a few times or edit with Pinta/GIMP. Was sorely missed in `maim` too.

A video of it in action (warning: loud music, `&mute=1` is broken): https://youtu.be/NB32QYt8WfI?t=6

I imagine this is far from trivial to implement (since this will probably require taking a screenshot upfront, instead of just rendering an overlay), but decided to request it anyway, who knows.

**Comment by emersion** [comment]
Yeah, I find this feature useful for precise screenshots. This can probably be done with the screencopy protocol.

**Comment by emersion** [comment]
Sorry, I'm going to -1 this as out-of-scope for slurp. Currently slurp doesn't capture the screen and I'd prefer it to stay simple like this. slurp's goal is to select, grim's role is to capture.

I'd encourage anyone who cares about this feature to start building a more feature-full screenshooting tool. I still think this feature would be very nice to have, but it probably makes more sense to implement it elsewhere.

**Comment by jeremejevs** [comment]
If slurp and grim isolation from each other is the main concern, then how about this: a mode where slurp can be supplied a path to an arbitrary image to select a region from, which may or may not be a fullscreen screenshot taken by grim a millisecond ago. Now that I've written this, it sounds like it could be a tool on its own, but then that tool and slurp would have so much overlap, that might as well go for a shared library. But, now there's the complexity of maintaining a library and caring about compatibility.

**Comment by emersion** [comment]
This won't be efficient at all -- this will use a lot of CPU and lag when playing e.g. videos (especially with multiple screen setups, for which it would be tricky to implement regardless).

I'd just fork grim+slurp into a unified program instead if I were to implement this.

**Comment by jeremejevs** [comment]
I think you misunderstood my proposal, I was thinking of something along the lines of this:

```bash
grim tmp.png
x=`slurp --image-to-select-from tmp.png -f "%wx%h+%x+%y"`
convert tmp.png -crop "${x}" screenshot.png
```

In this mode, slurp would just open `tmp.png` in a fullscreen window, with the same selection code. As a welcome side-effect, this would also make it easier to take screenshots of non-static content.

But I have no problem with having a separate tool, of course, just pitching this in case you haven't considered it. I'm against fragmentation, so I like to make sure it's unavoidable.

**Comment by emersion** [comment]
Then just use GIMP to select the region of the captured screenshot?

**Comment by jeremejevs** [comment]
Very poor ergonomics compared to slurp / ShareX / any other specialized tool. However, okay, slurp's job is "minimal Wayland selection tool", not "versatile screenshot-/screencast-oriented selection tool", so you're right, this is out of scope.
