### ISSUE TITLE
Cursor change does not work

### ISSUE THREAD

**Issue by eternal-sorrow** [emersion/slurp#14]
For some reason slurp uses the default arrow cursor.

**Comment by emersion** [comment]
Can you check whether this condition is triggered?

https://github.com/emersion/slurp/blob/0dbd03991462397eb92bb40af712c837c898ebf1/main.c#L481

**Comment by eternal-sorrow** [comment]
Yes, it is.

**Comment by emersion** [comment]
Then your cursor theme is missing the crosshair image. Maybe it has another name, like `tcross`?

**Comment by eternal-sorrow** [comment]
how do I check? How do I set cursor theme on sway 1.0 btw? It uses the default ugly pixel cursors when I hover window titles for example. slurp also uses them.

**Comment by emersion** [comment]
Try replacing `crosshair` with `tcross`.

Maybe your whole cursor theme is messed up? You can set it like so: https://wiki.archlinux.org/index.php/Cursor_themes

**Comment by eternal-sorrow** [comment]
OK, the problem was - I didn't have the `~/.icons` directory. only `~/.local/share/icons`. For GNOME and GTK apps it was enough, but not for sway and slurp apparently. adding the symlink fixed this issue.

**Comment by emersion** [comment]
Nice

**Comment by eternal-sorrow** [comment]
But I thought, the `~/.icons` is obsolete location and `~/.local/share/icons` is the correct XDG one. I'm wrong?

**Comment by emersion** [comment]
Ah. I'm not sure, slurp just uses libwayland-cursor, which does everything for us. The Arch wiki page only mentions `~/.icons/default/index.theme` it seems. Source?

**Comment by emersion** [comment]
Maybe related to https://github.com/swaywm/wlroots/issues/980?
