### ISSUE TITLE
Bug: Cursor is not updated on start

### ISSUE THREAD

**Issue by Limero** [emersion/slurp#15]
When you run slurp, the cursor will remain regular until you move it, and then, it will turn into the crosshair.

This causes a problem when running slurp and directly doing a selection, the selection will not be highlighted and the resulting selection will have an empty x and y value, like this: `0,0 1144x753`

Steps to replicate:
1. Open a terminal and run slurp
2. Don't move the cursor
3. Notice the cursor still being regular, not a crosshair
4. Press the primary mouse button and drag a selection
5. Notice the selection not being highlighted and the result having x/y values set to 0

**Comment by emersion** [comment]
This is actually a sway bug. Sway needs to rebase the cursor when re-ordering layer surfaces.

**Comment by Limero** [comment]
I see! Is there an open bug for this in Sway that I can follow?

**Comment by emersion** [comment]
No, please create one!

**Comment by emersion** [comment]
Closing because it's not our bug.
