### ISSUE TITLE
Ability to quick select windows similarly to slop

### ISSUE THREAD

**Issue by rileyinman** [emersion/slurp#16]
First off, thanks for creating such a useful tool for wayland desktops! The only thing missing to make it a complete replacement for me would be the ability to simply click on a window to select its coordinates, like `slop` does on x desktops. The feature is pretty handy to quickly grab something without having to manually select the exact border.

**Comment by emersion** [comment]
Indeed. We need a new Wayland protocol for this.

**Comment by mgrandl** [comment]
Yeah that would be awesome, though obviously challenging on Wayland.

**Comment by emersion** [comment]
Fixed in #28

```
swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp
```

**Comment by Photon89** [comment]
Hi, sorry for commenting on an already closed issue. I'm wondering whether there is a way to achieve this functionality for other DEs (say, KDE), that is, outside of sway. Thanks!

**Comment by necauqua** [comment]
Hey just in case you came here from google here's the one I just made for hyprland (I'm sure someone already did this somewhere but oh well)

```bash
hyprctl clients -j | jq --argjson active $(hyprctl monitors -j | jq -c '[.[].activeWorkspace.id]') '.[] | select((.hidden | not) and .workspace.id as $id | $active | contains([$id])) | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' -r | slurp
```

**Comment by PerchunPak** [comment]
The above comment didn't work for me, because of the missing parentheses. Here is the updated version

```sh
hyprctl clients -j | jq --argjson active $(hyprctl monitors -j | jq -c '[.[].activeWorkspace.id]') '.[] | select((.hidden | not) and (.workspace.id as $id | $active | contains([$id]))) | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' -r | slurp
```

(Added parentheses after word `and` in `select`)

**Comment by Schnouki** [comment]
For Sway, here's the updated command to also select floating windows:

```bash
swaymsg -t get_tree | jq -r '.. | ((.nodes? + .floating_nodes?) // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp
```

Saved this as `slurp-window` and using it with `wf-recorder -g $(slurp-window)` 😊
