### ISSUE TITLE
Start vertex appears in wrong position.

### ISSUE THREAD

**Issue by c-edw** [emersion/slurp#21]
This is quite difficult to replicate. When using slurp to make a selection *given the very specific scenario below*, the start vertex (where the mouse is dragging from) will appear in the wrong place.

Steps to replicate:

1. Configure Sway such that you have two monitors, one above the other
2. Set the following environment variables:
```
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
```
2. Open a tiling window of any kind on the left, and KeePassXC on the right (the only two applications it seems to happen with is KeePassXC as long as the above variables are set, and a Wayland compositor named Cage, suggesting that it only happens with Wayland applications)
3. Move your mouse to the very top right of the KeePassXC window. The crosshair should only be a pixel or two below the top of the screen, bearing in mind there's another monitor above.
4. Click and drag
5. Observe that the start vertex appears at the bottom centre of the screen

The screenshot shows what it looks like at step 5. The bottom left vertex behaves as the start vertex which is in the wrong place, because I started the selection at the top of the screen.

![162429-2019-01-26](https://user-images.githubusercontent.com/38229097/51790023-dfc45b80-2187-11e9-975b-b089e2b1568e.png)

**Comment by yorickvP** [comment]
If there's a monitor above, is it possible that you started the selection on that monitor? That would explain this effect, currently.

**Comment by c-edw** [comment]
The selection was started at the top of the same monitor.

**Comment by yorickvP** [comment]
Are you still seeing this bug with newer versions?

**Comment by c-edw** [comment]
Sorry for the late reply. I gave this a try and wasn't able to produce the issue, but it was difficult to demonstrate in the first place. I'll reopen this issue if I see it again.
