### ISSUE TITLE
segfault in wl_proxy_marshal via wl_surface_set_buffer_scale

### ISSUE THREAD

**Issue by Hello71** [emersion/slurp#22]
pointer->cursor_surface is NULL at main.c:38.

**Comment by emersion** [comment]
Can you share a WAYLAND_DEBUG=1 log of slurp when this happens?

**Comment by Hello71** [comment]
no, it works now. however, there is an interesting behavior that if I start slurp then immediately depress the mouse button, the crosshair is not shown, and start coordinate is incorrectly printed as "0,0". possibly this is related?

**Comment by emersion** [comment]
I don't think so, this was https://github.com/emersion/slurp/issues/26

**Comment by Hello71** [comment]
it works now so *shrug*
