### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by emersion** [emersion/slurp#3]

**Comment by pengux** [comment]
Sorry to comment in an old issue but it seems the HiDPI support stopped/doesn't work for me. When running `slurp -d` for example I can clearly see that the numbers are half of what they are supposed to be on my screen (3840 × 2400)

```
slurp -d
0,0 1919x1199
```

is there a flag to enable HiDPI support that I've missed?

**Comment by emersion** [comment]
>is there a flag to enable HiDPI support that I've missed?

No. If it doesn't work it's a bug.
