### ISSUE TITLE
Add a mode to select a single coordinate

### ISSUE THREAD

**Issue by schauveau** [emersion/slurp#34]
A mode to select a single coordinate instead of an area could be useful to implement various utilities for sway (using ipc get_tree) or other wayland compositors. 
- color picker
- screenshot of selected window.
- get information about selected window (class, role, app_id, geometry...)
- kill window under cursor (i.e. xkill)

**Comment by emersion** [comment]
I see how this could be useful for a color picker. Maybe we should add constraints like min-size and max-size.

To select a window, see https://github.com/emersion/slurp/pull/28
