### ISSUE TITLE
slurp ignores keyboard layout

### ISSUE THREAD

**Issue by buffet** [emersion/slurp#36]
I got `XKB_DEFAULT_OPTIONS='compose:ralt,caps:swapescape'` in my environment (using sway).

When I invoke slurp and try to cancel it with the Caps key nothing happens.
When I press the actual Esc key it gets cancelled, but caps lock gets triggered as well.

**Comment by emersion** [comment]
This happens because we use keycodes directly, not keybinds.

I'm not sure using libxkbcommon is worth it.

**Comment by buffet** [comment]
Yeah, for a single key it's definitely not worth it.
I feel like leaving it like this isn't a solution either though.

Maybe check `XKB_DEFAULT_OPTIONS` for `caps:swapescape` and `caps:escape` (is it only those two?) "manually" and just listen for a different keycode then?

**Comment by foxcpp** [comment]
xkb_options can be specified in sway (or other compositors) configuration file so using envvar is not reliable.

**Comment by emersion** [comment]
>xkb_options can be specified in sway (or other compositors) configuration file so using envvar is not reliable.

That's right, don't set XKB_DEFAULT_OPTIONS.

>Maybe check XKB_DEFAULT_OPTIONS for caps:swapescape and caps:escape (is it only those two?) "manually" and just listen for a different keycode then?

This sounds like a hack and won't scale, but I don't see a better alternative.

**Comment by jvanbruegge** [comment]
I also set `caps:escape` with `xkb_options` in sway, and it would be really nice to be able to abort slurp with capslock

**Comment by emersion** [comment]
According to https://gitlab.freedesktop.org/wayland/wayland/merge_requests/58 there's no way around loading the keymap. Interpreting the raw keycodes directly as we do now is wrong.

**Comment by NilsIrl** [comment]
I'm currently working on this.

**Comment by Zocker1999NET** [comment]
This is not working in my case, using sway 1.5.3 and slurp 1.2.0 (both from Debian Unstable). It may the case, that the solution #52 does not work if `caps:escape` is only configured for a single keyboard? This is the keyboard input relevant part of my sway config:
```
input 6127:24757:Chicony_ThinkPad_X1_Tablet_Thin_Keyboard_Gen_3 {
    xkb_layout de,us
    xkb_options grp:ctrls_toggle,grp_led:caps,caps:escape,altwin:menu,nbsp:level3,terminate:ctrl_alt_bksp
    #xkb_options grp:ctrls_toggle,caps:swapescape,altwin:menu,nbsp:level2,terminate:ctrl_alt_bksp
    repeat_delay 500
    repeat_rate 30
}
```
Other applications do recognize caps as escape without any further configuration.

**Comment by emersion** [comment]
The commit fixing this issue hasn't been released yet.
