### ISSUE TITLE
slurp with multi-monitor gives wrong coordinates

### ISSUE THREAD

**Issue by J0nnyMak0** [emersion/slurp#37]
When I use slurp to get an area on one of my external monitors, I end up getting the coordinates for the corresponding area on my primary built-in monitor instead.

EDIT: To be clearer, `grim -g '<coords>'` captures primary monitor instead.

`sway version 1.1-rc1-2-g51c07779 (May  6 2019, branch 'master')`

My monitor setup in config:
```
output eDP-1 pos 0 0 res 1920x1080 scale 1
workspace 1 output eDP-1
output DP-1 pos 1920 0 res 2560x1440 scale 1
workspace 9 output DP-1
output DP-3 pos 4480 240 res 1920x1200 scale 1
workspace 11 output DP-3
output VGA-1 pos 6400 56 res 1280x1024 scale 1
workspace 12 output VGA-1
```

**Comment by Half-Shot** [comment]
Seeing the same issue. 

I also notice that event selecting the whole output of the rightmost monitor doesn't give the correct dimensions either, as selecting the whole output (roughly) gives "1,1 3070x1727".

This works fine on the left output.

Outputs:
```
➜  ~ swaymsg -t get_outputs
Output DP-3 'Dell Inc. DELL P2415Q P2PC25220A8L' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 1080,0
  Scale factor: 1.250000
Output HDMI-A-1 'Dell Inc. DELL U2414H 9TG4645R4M7L'
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
```

**Comment by luispabon** [comment]
Seeing the same problem. In my case, it selects from the left-most output, which is not the primary. My displays are arranged like
```
[ secondary ] [ secondary ]
          [  primary  ]
```

or 
```
sway output HDMI-A-1 pos 0 0 res 1920x1080
sway output DP-2 pos 1921 0 res 1920x1080
sway output eDP-1 pos 960 1081 res 3840x2160
```

**Comment by NilsIrl** [comment]
I'm having a similar issue as well but from what I can tell, the problem is caused by grim rather than slurp. I have a vertical monitor and when I try to take screenshot of it, the screenshot is inverted.

**Comment by NilsIrl** [comment]
Okay, this seems to have been fixed and reported already: https://github.com/emersion/grim/issues/71

**Comment by luispabon** [comment]
Definitely fixed.
