### ISSUE TITLE
Man entry is wrong about # being optional

### ISSUE THREAD

**Issue by Mel34** [emersion/slurp#39]
```
man slurp(1)
COLORS
       Colors may be specified in #RRGGBB or #RRGGBBAA format. The # is op‐
       tional.
```
Specifying colors in -b -c and -s options with # prepended to RRGGBB or RRGGBBAA format outputs e.g.:
`slurp: option requires an argument -- 's'`
Ommiting # works as advertised.
Man entry is wrong about # being optional. It doesn't function if # is included in color definition.

**Comment by emersion** [comment]
Works for me:

```sh
slurp -b '#000000'
```

If you don't quote it, your shell will likely interpret it as a comment though.

**Comment by Mel34** [comment]
Thanks, I didn't quote it.
