### ISSUE TITLE
1.2.0 package not current with the repo at time of release

### ISSUE THREAD

**Issue by ainola** [emersion/slurp#40]
It appears that the 1.2.0 release package at https://github.com/emersion/slurp/releases/download/v1.2.0/slurp-1.2.0.tar.gz is not at the same revision as the source code artifact. For instance, the `-p` option is not included.

**Comment by emersion** [comment]
Gah, it seems I've messed up the release artifacts. I just updated them, can you confirm it's fixed now?

**Comment by ainola** [comment]
Yep, everything is fine, now! Thanks for all of your work :)
