### ISSUE TITLE
Make selection without affecting focus of window

### ISSUE THREAD

**Issue by pengux** [emersion/slurp#43]
Currently if a user is clicking on a dropdown menu in an application (for example a browser), making a selection will unfocus the window and makes the dropdown close. This prevents taking screenshots (with grim for example) of the content of the dropdown menu. Is there a way to make a selection without losing focus of the window?

**Comment by emersion** [comment]
You'd have the same issue if you want to screenshot a tooltip for instance.

You can introduce a delay between the selection and the actual screenshot:

```sh
geo="$(slurp)"; sleep 5; grim -h "$geo" out.png
```

Or you can shoot the whole output and crop the image afterwards.

**Comment by pengux** [comment]
I understand there are workarounds as you mentioned, but is there a way to fix this so it works without workarounds? I think the problem is that slurp is stealing focus when invoked?

**Comment by emersion** [comment]
Taking focus is necessary to exit on Esc keypress.

**Comment by pengux** [comment]
Is it possible to take focus only after the screenshot is taken?

**Comment by emersion** [comment]
Selection happens before the screenshot is taken.

**Comment by pengux** [comment]
> Selection happens before the screenshot is taken.

Yeah, what I meant was if it's possible to not take the focus until after the screenshot is taken. Or is the focus required for whole time?

**Comment by emersion** [comment]
slurp doesn't take screenshots.

**Comment by NilsIrl** [comment]
> Taking focus is necessary to exit on Esc keypress.

Not necessarily, `wshowkeys` works without taking focus.

This is a very important feature and the current behaviour makes slurp unusable
in many situations.

**Comment by emersion** [comment]
>Not necessarily, wshowkeys works without taking focus.

wshowkeys is suid root because it's basically a keylogger, so it can do that. I'm not willing to make slurp suid root.

>This is a very important feature and the current behaviour makes slurp unusable
in many situations.

Nobody forces you to use slurp. Feel free to patch it locally, fork it or to create a new project.

**Comment by Xyene** [comment]
Thanks for `slurp`!

In case someone else comes across this thread in the future, this is my workaround for being able to screenshot menus with `slurp` + `grim` in swaywm (since `slurp` + `grim` are recommended for screenshotting there).

```bash
#!/bin/bash
screenshot="$(mktemp --suffix screenshot.ppm)"
grim "${screenshot}"
feh "${screenshot}" &
feh_pid=$!

while [ -z "$(swaymsg -t get_tree | grep feh)" ]; do
  continue
done

gm convert -crop "$(slurp -d | perl -ne '/(\d+),(\d+) (.+)/;print"$3+$1+$2"')" "${screenshot}" png:- | wl-copy -t image/png
kill -SIGKILL ${feh_pid}
rm "${screenshot}"
```

And then, in `~/.config/sway/config`,

```
for_window [title="feh.*screenshot"] floating enable
for_window [title="feh.*screenshot"] fullscreen on
bindsym $mod+Shift+2 exec ~/.scripts/screenshot.sh
```

What this does is:

* Take a PPM-formatted screenshot with `grim` (saves PPM much faster than PNG)
* Open full-screen, floating `feh` (does not disturb other window placement)
* `slurp` over the `feh` canvas
* Use GraphicsMagick (feel free to substitute ImageMagick) to crop and convert to PNG
* Copy to clipboard
* Kill `feh` and clean up

**Comment by pengux** [comment]
@Xyene Thanks for the script! But it seems like `feh` does not work for me with a Hidpi screen. I've replaced it with `imv` instead:

`~/.scripts/screenshot.sh`
```
#!/bin/bash

if pidof -o %PPID -x "$0"; then
  exit 0
fi

screenshot="$(mktemp --suffix screenshot.ppm)"
grim -t ppm "${screenshot}"
imv "${screenshot}" &
imv_pid=$!

while [ -z "$(swaymsg -t get_tree | grep imv)" ]; do
  continue
done

convert -crop "$(slurp -d | perl -ne '/(\d+),(\d+) (.+)/;print"$3+$1+$2"')" "${screenshot}" png:- | wl-copy -t image/png
kill -SIGKILL ${imv_pid}
rm "${screenshot}"
```

`~/.config/sway/config`
```
for_window [title="imv.*screenshot"] floating enable
for_window [title="imv.*screenshot"] fullscreen on
bindsym $mod+Control+Shift+2 exec ~/.scripts/screenshot.sh
```

**Comment by fseitun** [comment]
@pengux did you find a clean workaround to this issue? Even at the cost of using a different library.

**Comment by pengux** [comment]
@fseitun no clean workaround I'm afraid. Either using `feh` above or do a fullscreen + crop.
