### ISSUE TITLE
Crosshair cursor is not scaled on 4k display

### ISSUE THREAD

**Issue by nostdm** [emersion/slurp#57]
It seems that when the selection cursor appears (crosshair) it's half the size of a normal cursor on a 4k display. Could this be a problem with the cursor theme? I tried elementary and adwaita cursor themes with the same result. How does slurp determine the size/theme of the crosshair cursor?

**Comment by ferrreo** [comment]
This kinda makes slurp unusable at higher resolutions, it is so small I can't see it 90% of the time, I'll have a go at fixing it

**Comment by BANanaD3V** [comment]
Any updates?
