### ISSUE TITLE
Remove %m flag usage

### ISSUE THREAD

**Issue by emersion** [emersion/slurp#68]
```
../main.c: In function ‘main’:
../main.c:822:21: error: ISO C does not support the 'm' scanf flag [-Werror=format=]
  822 |    if (sscanf(line, "%d,%d %dx%d %m[^\n]", &in_box.x, &in_box.y,
      |                     ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by tmccombs** [comment]
That's unfortunate. Without the m modifier, we would either need to have a maximum label length, or extract the rest of the line differently (outside of sscanf) to remove it.

Fwiw, The %m modifier is part of the posix standard (https://pubs.opengroup.org/onlinepubs/9699919799/).

**Comment by emersion** [comment]
Eh. If this is POSIX. all is fine. I wonder why GCC complains.

**Comment by tmccombs** [comment]
It's a posix extension to the ISO std. My guess is the purpose of the warning is to warn that it wouldn't be portable to a non-posix system.
