### ISSUE TITLE
Allow skipping the click to select

### ISSUE THREAD

**Issue by Kommynct** [emersion/slurp#73]
This would be useful for the output selection mode.

**Comment by tmccombs** [comment]
Could clarify what you mean by that? What exactly is the behavior you want?

**Comment by Kommynct** [comment]
Sorry, my bad, for example: on sway i have this setup

bindsym --no-repeat mod1+mod4+p exec grim -g "$(slurp -o -b 00000000 -s 00000000 -w 0)" 

However, this could be optimized by making it so that when i push the keybind it instantly screenshots the output the cursor is on, rather than after a click.

Is that completely clear?

**Comment by tmccombs** [comment]
Ah, I think that makes sense. You want to use the current location of the mouse as input, rather than the location when the user clicks?

**Comment by Kommynct** [comment]
Exactly.

**Comment by emersion** [comment]
The output the cursor is on is available via `swaymsg`. There's no need for slurp here.

**Comment by Kommynct** [comment]
...i'm dumb

**Comment by emersion** [comment]
Eh, no worries :)
