### ISSUE TITLE
Add Single-pixel selection as full-screen selection

### ISSUE THREAD

**Issue by bagnaram** [emersion/slurp#98]
It would be a nice addition if slurp would treat a single pixel-sized selection as the entire screen. Perhaps as an optional flag of sorts. This would mimic the function of `scrot` for handling full screen selections.

**Comment by emersion** [comment]
This can be easily handled in a wrapper script.

**Comment by bagnaram** [comment]
The current way I see it would be kind of difficult with a single run script because you can only invoke with single pixel selection or rectangular selection, not both. When rectangular is enabled, it treats a single pixel a s a cancellation. My proposal is to add an option to fall-back to full-screen when a single pixel is selected in rectangular mode. 

I will take a crack at adding this option

**Comment by emersion** [comment]
An alternate option would be an option which adds the whole desktop as a predefined rectangle.

**Comment by tmccombs** [comment]
Does the `-o` option not do what you want? If you do a single click it will select the whole output, but you can still select a rectangle (unless you also use the `-r` option).

**Comment by bagnaram** [comment]
I guess it does. I am not sure if it is a side effect of `box_output` being initialized default in `output_from_surface` but it is the effect I am intending to have. Many thanks, won't need that PR after all.

**Comment by tmccombs** [comment]
I'm pretty sure that is the intended behavior of `-o`.

**Comment by emersion** [comment]
Yes, `-o` will make it so a click will select one of the outputs.
